"use client";

export function SimDisclaimer() {
  return (
    <div className="disclaimer-banner">
      <strong>Scenario simulation, not a prediction.</strong>{" "}
      Outcome probabilities are Monte Carlo estimates based on available data. Narrative
      reactions are generated by an unbenchmarked multi-agent simulation — LLM crowds
      over-polarize compared to real populations. All narrative posts are synthetic.
    </div>
  );
}
